import type { Metadata } from "next";
import { NOTICE_PACKAGES, NOTICE_SOURCE, noticeGroups } from "@/lib/site/third-party-notices";
import { SitePage } from "../../site-page";

export const metadata: Metadata = {
  title: "Third-party notices · 41Prompts",
  description:
    "Every third-party package this service runs on, with the licence each one declares. Generated from the package manager, not typed.",
  alternates: { canonical: "/legal/third-party-notices" }
};

/**
 * The notices page `docs/roadmap.md` asks for in two places, generated rather than written.
 *
 * It lists what is **distributed** — the dependency closure of what runs in production — rather than
 * the whole workspace, and `lib/site/third-party-notices.ts` carries the argument for that choice.
 */
export default function ThirdPartyNoticesPage() {
  const groups = noticeGroups();

  return (
    <SitePage
      current="security"
      eyebrow="Legal"
      heading="Third-party notices"
      lede={
        <>
          41Prompts runs on {NOTICE_PACKAGES.length} third-party packages under {groups.length} licences. This list is
          generated by <span className="mono">{NOTICE_SOURCE}</span> and regenerated by a test, so it cannot quietly
          fall behind what is installed.
        </>
      }
    >
      <div className="site-wrap">
        <div className="site-card">
          {groups.map((group) => (
            <div className="site-row" key={group.license} id={group.license.replace(/[^A-Za-z0-9.-]+/g, "-")}>
              <div className="site-row-key">
                <b>{group.license}</b>
                <span>{group.packages.length === 1 ? "1 package" : `${group.packages.length} packages`}</span>
              </div>
              <div className="site-row-body">
                <ul className="legal-list">
                  {group.packages.map((entry) => (
                    <li key={`${entry.name}@${entry.version}`}>
                      <span className="mono">
                        {entry.name}@{entry.version}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>
        <p className="site-lede">
          The four packages 41Prompts publishes — <span className="mono">@41prompts/core</span>,{" "}
          <span className="mono">@41prompts/sdk</span>, <span className="mono">@41prompts/cli</span> and{" "}
          <span className="mono">41p</span> — have no third-party dependencies of their own, and neither does{" "}
          <span className="mono">fortyone-prompts</span>. Nothing above reaches your application through them.
        </p>
      </div>
    </SitePage>
  );
}
