/**
 * The file the Connect page shows — **generated by `@41prompts/core`** since EPIC-053.
 *
 * ## This module used to be the generator. It is now a seam, and that is the whole change
 *
 * EPIC-055 wrote the generator here, because the Connect page was the only thing that needed it and
 * `41p pull` did not exist. Its ruling 3 said what would happen when it did: *"when EPIC-053 ships
 * `41p pull`, this is precisely the file it will write"*.
 *
 * `CLAUDE.md` rule 11 forbids `packages/cli` importing `apps/*`, so the CLI could not call this
 * where it lived, and copying it would have made two implementations of one file format — the
 * defect this repository has refused three times already (two copies of an env placeholder, two of
 * `buildHashOf`, two of the publish gate), each time for the same reason: **the copy goes stale
 * silently**, and the stale one here writes into a customer's repository.
 *
 * So the generator moved to `packages/core/src/codegen/`, which is pure TypeScript with no IO and no
 * DOM and is where `CLAUDE.md` rule 1 puts logic that must be correct. This module re-exports it
 * under the names the page already imports, so the page's own diff for EPIC-053 is one clause of
 * copy rather than an import rewrite.
 *
 * **One thing a reader will notice changed:** the generated header. EPIC-055's said *"copy this into
 * your project"*; it now carries `docs/roadmap.md`'s ownership sentence, because a file a command
 * writes into your repository should say who owns it. EPIC-053 ruling 9.
 */

import {
  identifierFor,
  identifiersFor,
  typescriptPromptsFile,
  type CodegenPrompt,
} from "@41prompts/core";

/** What the Connect page calls a row. `CodegenPrompt` is the same shape; the alias keeps the page's vocabulary. */
export type ConnectPrompt = CodegenPrompt;

export { identifierFor, identifiersFor };

/** The generated `prompts.ts`. One function, two callers — this page and `41p pull`. */
export const generatedPromptsFile = typescriptPromptsFile;
