// SPDX-FileCopyrightText: 2026 41Prompts Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * The first lines of every generated bindings file, in both languages (EPIC-053).
 *
 * ## The ownership sentence is `docs/roadmap.md`'s, verbatim, and it is the point
 *
 * > *`pull` (typed `prompts.ts`/`.py` by prompt id, lockfile, bundled artifacts; header "This file
 * > is yours; 41Prompts claims no rights in it")*
 *
 * A generated file is the one thing this product writes that ends up committed inside somebody
 * else's repository, under their licence, in their history. Most tools that write into a customer's
 * tree say nothing about who owns the result, and the answer people assume in the absence of a
 * sentence is usually the wrong one. So it is not decoration and not a comment somebody may reword:
 * `LICENCE_LINE` is exported on its own and asserted as a literal, so a future language's generator
 * cannot paraphrase it and a tidy-up cannot soften it.
 *
 * **This replaces the header EPIC-055 shipped** (*"prompts.ts — copy this into your project."*). The
 * two are merged rather than one deleting the other: the ownership line is the roadmap's and is
 * load-bearing, and the "regenerate it" line is how a reader knows the file is derived and should
 * not be hand-edited. Both callers emit this because both call this function (ruling 1), so the
 * Connect page's wording changes in this epic — expected, and recorded in ruling 9.
 *
 * The comment prefix is the only thing that differs between the two languages. Writing the header
 * once with a prefix rather than twice with different punctuation is the same argument as the rest
 * of this directory: a sentence that exists in two places drifts in one of them.
 */

/** `docs/roadmap.md`'s sentence. Never reworded; asserted as a literal. */
export const LICENCE_LINE = "This file is yours; 41Prompts claims no rights in it.";

/** The header for one language, as comment lines. `comment` is `//` or `#`. */
export function headerFor(filename: string, comment: string): string[] {
  return [
    `${comment} ${filename} — generated by 41Prompts.`,
    `${comment} ${LICENCE_LINE}`,
    `${comment} One function per prompt in this project. Regenerate it when you add one.`,
  ];
}
