import type { Metadata } from "next";
import { exampleFor, runningExample, RUNNING_EXAMPLE_NAME } from "@/lib/site/article-examples";
import { FINDINGS_IN_ORDER } from "@/lib/site/finding-copy";
import { SiteFooter, SiteNav } from "../../site-chrome";

export const metadata: Metadata = {
  title: "What your prompt does not check · 41Prompts",
  description:
    "Six things a prompt can be wrong about that nothing will catch: contradictions, rules with no check, rules that cannot be checked, repetition, padding, and passages doing too much. With real examples.",
  alternates: { canonical: "/guides/what-your-prompt-does-not-check" },
  openGraph: {
    type: "article",
    title: "What your prompt does not check",
    description: "Six things a prompt can be wrong about that nothing will catch, with real examples."
  }
  // The card image comes from `opengraph-image.tsx` in this segment, which overrides the site-wide
  // one — a link to the article should unfurl as the article, not as the home page.
};

/**
 * The one content asset of Stage 1 (EPIC-015 decision 4).
 *
 * It is read by a sceptical engineer and by a model deciding whether to cite us, and both punish the
 * same thing: a claim the product cannot back. So **every example on this page is generated by running
 * the real detectors over the committed corpus** (`lib/site/article-examples.ts`) rather than written
 * out by hand, and `article-examples.test.ts` fails if any of the six stops being produced.
 *
 * There is no call to sign up, because there is nothing to sign up for.
 */
export default function ArticlePage() {
  const { source, findings } = runningExample();
  const counted = new Map<string, number>();
  for (const finding of findings) counted.set(finding.kind, (counted.get(finding.kind) ?? 0) + 1);

  return (
    <>
      <a className="skip-link" href="#main">
        Skip to content
      </a>
      <SiteNav />

      <main className="prose-page" id="main">
        <article>
          <p className="eyebrow">Guide</p>
          <h1>What your prompt does not check</h1>

          <p>
            A prompt is a set of rules written in prose. Some of those rules are enforced by something
            — a JSON parser downstream, a schema, a test. Most are not: they hold because the model
            usually does what it is told, and they stop holding quietly, on a day when it does not.
          </p>
          <p>
            There are six ways we know how to find that, deterministically, without asking a model for
            an opinion. Each one below has a real example, taken from the corpus this product is
            tested against — nothing here is invented for the article.
          </p>

          <h2>The prompt these examples come from</h2>
          <p>
            A support-email router. Roughly two hundred words, the kind of thing that works well enough
            in production that nobody re-reads it. It is{" "}
            <code>{RUNNING_EXAMPLE_NAME}</code> in the test corpus, and the decompiler finds{" "}
            {findings.length} things in it.
          </p>
          {/* Focusable and labelled: it scrolls, and a region that scrolls but cannot be reached by
              keyboard is unusable for anyone not holding a mouse — axe's `scrollable-region-focusable`,
              which caught this. */}
          <pre className="article-source" tabIndex={0} role="region" aria-label={`The ${RUNNING_EXAMPLE_NAME} prompt`}>
            {source}
          </pre>

          <h2>The six findings</h2>

          {FINDINGS_IN_ORDER.map(([kind, copy]) => {
            const example = exampleFor(kind);
            const inRunning = counted.get(kind) ?? 0;
            return (
              <section key={kind} className="article-finding">
                <h3>{copy.name}</h3>
                <p>{copy.summary}</p>
                {example !== undefined && (
                  <figure className="article-example">
                    <blockquote>{example.message}</blockquote>
                    {example.suggestion !== undefined && <p className="article-suggestion">{example.suggestion}</p>}
                    <figcaption>
                      {inRunning > 0
                        ? `From the prompt above — ${inRunning} of these in it.`
                        : `From ${example.fixture} in the test corpus.`}
                    </figcaption>
                  </figure>
                )}
              </section>
            );
          })}

          <h2>Try it on your own</h2>
          <p>
            Paste a prompt you already run in production and see which of these it has. It takes one
            paste — there is no account, nothing is stored, and there is nothing to install.
          </p>
          <p>
            <a className="btn btn-pri article-cta" href="/decompile">
              Open the decompiler
            </a>
          </p>

          <h2>What this does not do</h2>
          <p>
            It does not rewrite your prompt, run it against a model, or score it. There is no editor
            yet. What it does is tell you, precisely and with the text in front of you, which of your
            rules nothing would catch — and that turns out to be most of them.
          </p>
        </article>
      </main>

      <SiteFooter />
    </>
  );
}
